In [ ]:
import numpy as np

In [ ]:
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

Convert Python List to Numpy Array

In [ ]:
np_arr_str = np.array(arr_str)
print(np_arr_str)

['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']


In [ ]:
arr_num = [5, 4, 6, 7, 3]
np_arr_num = np.array(arr_num)
print(np_arr_num)

[5 4 6 7 3]


In [ ]:
type(np_arr_num)

numpy.ndarray

In [ ]:
type(np_arr_str)

numpy.ndarray

Numpy Matrix

In [ ]:
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)
print(type(matrix))

[[1 2 1]
 [4 5 9]
 [1 8 9]]
<class 'numpy.ndarray'>


Numpy arange

In [ ]:
arr2 = np.arange(start=0,stop=10,step=2)
print(arr2)

[0 2 4 6 8]


linspace

In [ ]:
matrix2 = np.linspace(0,10)
print(matrix2)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


ones

In [ ]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

zeros

In [ ]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

eye

In [ ]:
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Reshape

In [ ]:
vec = np.arange(0,10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
vec.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Arithmetic Operations

In [ ]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
print(arr1)
print(arr2)
print(arr1 + arr2)
print(1/arr1)
print(arr1**2)


[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[1.         0.5        0.33333333 0.25       0.2       ]
[ 1  4  9 16 25]


Matrix Operations

In [ ]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.arange(1,5).reshape(2,2)
print(mat1)
print(mat2)
print(mat1 + mat2)
print(mat1 * mat2 )
print(mat1 @ mat2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


Transpose

In [ ]:
np.transpose(mat1)

array([[1, 3],
       [2, 4]])

Random

In [ ]:
np.random.rand(5,5)

array([[0.24949724, 0.63728537, 0.96972789, 0.62130695, 0.42962562],
       [0.39861158, 0.32153585, 0.18195702, 0.64052144, 0.11469356],
       [0.01540705, 0.42012362, 0.46692306, 0.57492109, 0.79242937],
       [0.84455385, 0.42332858, 0.45751176, 0.20767198, 0.68600815],
       [0.80748158, 0.28974379, 0.91649767, 0.41882737, 0.95959371]])

In [ ]:
np.random.randn(5,5)

array([[ 0.06085807,  0.00403371,  0.39107475,  1.24513613, -0.45869571],
       [-1.19263585,  1.52831876, -1.35633789,  0.2496621 , -1.40859376],
       [-1.90895262,  1.30128149,  0.24182205,  0.04302932, -0.49992133],
       [-0.03534111, -0.02286696,  0.36724959, -1.96130824, -0.07589517],
       [-0.34901222,  2.05599468, -0.46691769, -0.30491604,  1.52416013]])

In [ ]:
np.random.randint(1,10,10)

array([7, 6, 6, 7, 3, 5, 4, 8, 8, 3])

In [ ]:
np.random.randint(1,10,(2,3))

array([[2, 3, 2],
       [4, 4, 1]])

Accessing Numpy Array

In [ ]:
rand_arr = np.random.randn(10)
print(rand_arr)

[ 1.46882385 -0.90778468 -0.26077512  1.30999438  1.21405827 -0.30174181
 -0.82424943 -1.48652503  0.16988453  0.71143142]


In [ ]:
rand_arr[0:2]

array([ 1.46882385, -0.90778468])

In [ ]:
rand_arr[rand_arr>0]

array([1.46882385, 1.30999438, 1.21405827, 0.16988453, 0.71143142])

In [ ]:
rand_mat = np.random.randn(5,5)
print(rand_mat)

[[-0.29633388  0.0761259   1.0362237   1.23194634 -0.9207978 ]
 [ 0.17846001 -0.70715456  0.19271312 -0.04634528 -0.28313952]
 [ 2.48944907 -0.9261824  -1.01525041  0.4530721   0.09425384]
 [ 0.59156008  0.10975031  1.18661823 -0.31133899 -0.71362874]
 [-0.93714026  0.04442783 -0.52921805 -0.26813544 -1.28853504]]


In [ ]:
rand_mat[0:2,0:2]

array([[-0.29633388,  0.0761259 ],
       [ 0.17846001, -0.70715456]])

Modify array and matrix entries

In [ ]:
rand_arr[3:5] = 5
print(rand_arr)

[ 1.46882385 -0.90778468 -0.26077512  5.          5.         -0.30174181
 -0.82424943 -1.48652503  0.16988453  0.71143142]


In [ ]:
rand_arr[rand_arr>0] = 1
print(rand_arr)

[ 1.         -0.90778468 -0.26077512  1.          1.         -0.30174181
 -0.82424943 -1.48652503  1.          1.        ]


In [ ]:
rand_mat[1:3,1:3] = 0
print(rand_mat)

[[-0.29633388  0.0761259   1.0362237   1.23194634 -0.9207978 ]
 [ 0.17846001  0.          0.         -0.04634528 -0.28313952]
 [ 2.48944907  0.          0.          0.4530721   0.09425384]
 [ 0.59156008  0.10975031  1.18661823 -0.31133899 -0.71362874]
 [-0.93714026  0.04442783 -0.52921805 -0.26813544 -1.28853504]]


In [ ]:
sub_mat = rand_mat[1:3,1:3]
print(sub_mat)

[[0. 0.]
 [0. 0.]]


In [ ]:
sub_mat[:] = 5
print(sub_mat)

[[5. 5.]
 [5. 5.]]


In [ ]:
print(rand_mat)

[[-0.29633388  0.0761259   1.0362237   1.23194634 -0.9207978 ]
 [ 0.17846001  5.          5.         -0.04634528 -0.28313952]
 [ 2.48944907  5.          5.          0.4530721   0.09425384]
 [ 0.59156008  0.10975031  1.18661823 -0.31133899 -0.71362874]
 [-0.93714026  0.04442783 -0.52921805 -0.26813544 -1.28853504]]


In [ ]:
sub_mat1 = rand_mat[1:3,1:3].copy()
print(sub_mat1)

[[5. 5.]
 [5. 5.]]


In [ ]:
sub_mat1[:] = 0
print(sub_mat1)

[[0. 0.]
 [0. 0.]]


In [ ]:
print(rand_mat)

[[-0.29633388  0.0761259   1.0362237   1.23194634 -0.9207978 ]
 [ 0.17846001  5.          5.         -0.04634528 -0.28313952]
 [ 2.48944907  5.          5.          0.4530721   0.09425384]
 [ 0.59156008  0.10975031  1.18661823 -0.31133899 -0.71362874]
 [-0.93714026  0.04442783 -0.52921805 -0.26813544 -1.28853504]]


Saving and Loading

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
randint_mat = np.random.randint(1,10,10).reshape(2,5)
print(randint_mat)
randint_mat2 = np.random.randint(1,10,10).reshape(2,5)
print(randint_mat2)

[[5 8 7 6 4]
 [7 7 7 4 9]]
[[6 2 8 9 2]
 [2 2 2 5 3]]


In [ ]:
np.save('/content/drive/MyDrive/numpy_mats',randint_mat)

In [ ]:
np.savez('/content/drive/MyDrive/numpy_mats_all',mat1=randint_mat,mat2=randint_mat2)

In [ ]:
loaded_arr = np.load('/content/drive/MyDrive/numpy_mats.npy')
print(loaded_arr)

[[5 8 7 6 4]
 [7 7 7 4 9]]


In [ ]:
loaded_multi = np.load('/content/drive/MyDrive/numpy_mats_all.npz')
print(loaded_multi['mat1'])
print(loaded_multi['mat2'])

[[5 8 7 6 4]
 [7 7 7 4 9]]
[[6 2 8 9 2]
 [2 2 2 5 3]]
